version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P YourStrongPassword123 -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: